main:
  - name: 首页
    url: /
    weight: 10
  - name: 研究
    url: /#research
    weight: 20
  - name: 论文
    url: /#papers
    weight: 30
  - name: 动态
    url: /#news
    weight: 35
  - name: 联系方式
    url: /contact/
    weight: 40
